config/routes.rb
Calendar::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :events, only: [:new,:create,:update,:destroy]

  root to: "static_pages#home"
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy", via: :delete

  match '/events/get_events'
  match '/events/resize'
  match '/events/move'
  match '/events/destroy'
  match '/events/edit'
  match '/events/select_partner'
  match '/events/get_pevents', via: :post

 

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true 	

  has_many :events, dependent: :destroy
  has_many :event_sets, dependent: :destroy


  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:show, :edit, :update]
  before_filter :correct_user,   only: [:show, :edit, :update]
  before_filter :admin_permission, only: [:new,:create]
  def new
  	@user=User.new
  end

  def show
  	@user= User.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to EasyURL, thanks for using our service"
      sign_in(@user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
  end

  def admin_permission
		redirect_to root_url unless admin?
  end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
-provide(:title, "Edit User")  
%h1 Update your profile

.row
  .span6.offset3
    = form_for(@user) do |f| 
      = render 'shared/error_messages' , object: @user

      = f.label :name 
      = f.text_field :name 

      = f.label :email 
      = f.text_field :email 

      = f.label :password 
      = f.password_field :password 

      = f.label :password_confirmation, "Confirm Password" 
      = f.password_field :password_confirmation 

      = f.submit "Save changes", class: "btn btn-large btn-primary" 

app/views/users/new.html.haml
-provide(:title, 'Sign up')
%h1 Create new user
.row
  .span6.offset3
    = form_for(@user) do |f| 

      =f.label :name
      =f.text_field :name

      =f.label :email
      =f.text_field :email

      =f.label :password
      =f.password_field :password

      = f.label :password_confirmation, "Confirmation" 
      = f.password_field :password_confirmation 

      = f.submit "Create account", class: "btn btn-large btn-primary" 

app/views/users/show.html.haml
-provide(:title, "#{@user.name}")  
.mybody
  .btn-group.page-header
    =link_to 'CREATE', new_event_path, class: "btn btn-large btn-success"
    =link_to 'PARTNER\'S CALENDAR', events_select_partner_path, remote: :true, class: "btn btn-large btn-primary"
  .span12.mybody
    #calendar1
    #desc_dialog{style: "display:none"}
      #event_info
        <b>Desciption </b>
        %span#event_desc
        %br       
        <b>Position </b>
        %span#event_position
        %br
        <b> From: </b>
        %span#event_from      
        %br
        <b> To : </b>
        %span#event_to
        %br
      #event_actions
        #btn-group.btn-group.pull-right.action-btn


%script{:type => 'text/javascript'}
  $(document).ready(function(){
  $('#calendar1').fullCalendar({
  editable: true,
  header: {
  left: 'prev,next today',
  center: 'title',
  right: 'month,agendaWeek,agendaDay'
  },
  defaultView: 'month',
  height: 600,
  width: 940,
  slotMinutes: 30,
  loading: function(bool){
  if (bool) 
  $('#loading').show();
  else 
  $('#loading').hide();
  },
  events: '../events/get_events',
  timeFormat: 'h:mm t{ - h:mm t} ', 
  });
  });