config/routes.rb
Calendar::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :events, only: [:new,:create,:update,:destroy]

  root to: "static_pages#home"
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy", via: :delete

  match '/events/get_events'
  match '/events/resize'
  match '/events/move'
  match '/events/destroy'
  match '/events/edit'
  match '/events/select_partner'
  match '/events/get_pevents', via: :post

 

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :allDay,:color, :desc, :from, :name, :position, :privacy, :to, :user_id,
  :fromtime, :fromdate, :totime, :todate,:period, :frequency, :times, :event_set_id
  attr_accessor :period, :frequency, :commit, :fromtime, :fromdate, :totime, :todate, :times

  validates :name, presence:true, length: {minimum: 4, maximum: 100}
  validates :user_id, presence: true
  validates :from, presence: true
  validates :to, presence: true
  validate :valid_to
  VALID_COLOR_REGEX = /^#(([a-fA-F0-9]){3}){1,2}$/
  validates :color, format: { with: VALID_COLOR_REGEX }
  belongs_to :user
  belongs_to :event_set

  after_initialize :get_datetimes
	before_validation :set_datetimes # convert accessors back to db format
  default_scope order: 'events.created_at DESC'

  REPEATS = [
    "Does not repeat",
    "Daily"          ,
    "Weekly"         ,
    "Monthly"        ,
    "Yearly"         
  ]

  def set_datetimes
    self.fromtime||="00"
    self.totime||="01"
    self.from = "#{self.fromdate} #{self.fromtime}:00" # convert the two fields back to db
    self.to = "#{self.todate} #{self.totime}:00"
  end  

  def get_datetimes
   	self.from ||= Time.now  # if the published_at time is not set, set it to now
   	self.to ||= 1.hour.from_now # if the published_at time is not set, set it to now

   	self.fromdate ||= self.from.to_date.strftime('%d-%m-%Y') # extract the date is yyyy-mm-dd format
   	self.fromtime ||= "#{'%02d' % self.from.hour}:#{'%02d' % self.from.min}" unless self.allDay # extract the time

   	self.todate ||= self.to.to_date.strftime('%d-%m-%Y') # extract the date is yyyy-mm-dd format
   	self.totime ||= "#{'%02d' % self.to.hour}:#{'%02d' % self.to.min}" unless self.allDay # extract the time
  end

  def update_events(events, event)
    events.each do |e|
      begin 
        st, et = e.to, e.from
        e.attributes = event
        if event_set.period.downcase == 'monthly' or event_set.period.downcase == 'yearly'
          nst = DateTime.parse("#{e.from.hour}:#{e.from.min}:#{e.from.sec}, #{e.from.day}-#{st.month}-#{st.year}")  
          net = DateTime.parse("#{e.to.hour}:#{e.to.min}:#{e.to.sec}, #{e.to.day}-#{et.month}-#{et.year}")
        else
          nst = DateTime.parse("#{e.from.hour}:#{e.from.min}:#{e.from.sec}, #{st.day}-#{st.month}-#{st.year}")  
          net = DateTime.parse("#{e.to.hour}:#{e.to.min}:#{e.to.sec}, #{et.day}-#{et.month}-#{et.year}")
        end
      rescue
        nst = net = nil
      end
      if nst and net
        e.from, e.to = nst, net
        e.save
      end
    end
    
    event_set.attributes = event
    event_set.save
  end


  def valid_to
    errors.add(:to,"time must be greater than the from time") unless to > from
  end

end
# == Schema Information
#
# Table name: events
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  from       :datetime
#  to         :datetime
#  position   :string(255)
#  desc       :string(255)
#  color      :string(255)     default("0")
#  privacy    :integer         default(0)
#  work       :boolean
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  allDay     :boolean
#

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :correct_user, only: [:destroy, :edit, :update,:move, :resize]
  before_filter :signed_in_user
	def index
	end

	def new
		@event = Event.new
	end

	def create
		if(params[:event][:period] == "Does not repeat")
      @event = current_user.events.build(params[:event])
      if @event.save
			 flash[:success] = "Created new event"
			 redirect_to root_url
		  else
			 render 'new'
		  end
    else 
      @event_set = current_user.event_sets.build(params[:event])
      if @event_set.save
       flash[:success] = "Created new event"
       redirect_to root_url
      else
       redirect_to new_event_path
      end
    end
	end

  def select_partner    
    @users = User.find(:all, :conditions =>"id != #{current_user.id}")
      if @users
        respond_to do |format|
          format.js
        end
      end
  end

  def get_pevents
    @users=User.find(params[:user_ids])
    pevents=[]
    @users.each_with_index do |user,index|
      results = user.events.all#find(:all, :conditions => ["privacy != 2"])
      results.each do |result|
        pcolor = get_color(index)
        pevents<<{:id => result.id, :title => result.name, :description => result.desc, :color => pcolor, :start => "#{result.from.iso8601}", :end => "#{result.to.iso8601}",:allDay => result.allDay}
        end
    end
    @pevents = pevents.to_json.html_safe
  end

	def get_events
  	@events = current_user.events.all
  	events = [] 
  	@events.each do |event|
        if(event.event_set)
    		  events << {:id => event.id, :title => event.name, :description => event.desc,:position => event.position, :color => event.color, :start => "#{event.from.iso8601}", :end => "#{event.to.iso8601}",:allDay => event.allDay, :recurring => true}
        else
          events << {:id => event.id, :title => event.name, :description => event.desc,:position => event.position, :color => event.color, :start => "#{event.from.iso8601}", :end => "#{event.to.iso8601}",:allDay => event.allDay}
        end
  	end
  	render :text => events.to_json
  	end

  def move
    @event = Event.find_by_id params[:id]
    if @event
      new_from = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.from))
      new_to = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.to))
      @event.update_attribute("allDay",params[:allDay])
      @event.update_attribute("from", new_from)
      @event.update_attribute("to", new_to)
    end
    respond_to do |format|
      format.js
    end
  end
  
  
  def resize
    @event = Event.find_by_id params[:id]    
    if @event
      new_to = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.to))
      @event.update_attribute("to",new_to)
    end

    respond_to do |format|
      format.js
    end    
  end
  
  def edit
    @event = Event.find_by_id(params[:id])
    respond_to do |format|
      format.js
    end
  end
  
  def update
    @event = Event.find(params[:id])
    if params[:commit] == "Update All Occurrence"
      @events = @event.event_set.events
      @event.update_events(@events, params[:event])
    elsif params[:commit] == "Update All Following Occurrence"
      @events = @event.event_set.events.find(:all, :conditions => ["'from' > '#{@event.from.to_formatted_s(:db)}' "])
      @event.update_events(@events, params[:event])
    else
      @event.update_attributes(params[:event])
      @event.save
    end

    respond_to do |format|
      format.js       
    end
    
  end  
  
  def destroy
    @event = Event.find_by_id(params[:id])
    if params[:delete_all] == 'true'
      @event.event_set.destroy
    elsif params[:delete_all] == 'future'
      @events = @event.event_set.events.find(:all, :conditions => ["'from' > '#{@event.from.to_formatted_s(:db)}' "])
      @event.event_set.events.delete(@events)
    else
      @event.destroy
    end
    
    respond_to do |format|
      format.js       
    end
    
  end

  private
  	def correct_user
      @event = current_user.events.find_by_id(params[:id])
      redirect_to root_url if @event.nil?
  	end

    def signed_in_user
      redirect_to root_url unless signed_in?
    end

    def get_color(index)
      color=['#FF6600','#008000','#FF99CC','#800080','#3366FF',
              '#99CCFF','#33CCCC','#993300','#333399','#FF00FF']
      return color[index]
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_colorpicker.html.haml
-10.times do |i|	
    =f.radio_button :color, i

app/views/events/_edit_form.html.haml
=form_for(@event, :html =>{class: "event-form"}, remote: true) do |f| 
  .modal-header
    %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} ×
    %h3#myModalLabel Edit events
  .modal-body
    %table.mytable
      =form_for(@event) do |f| 
        = render 'shared/error_messages' , object: @event
        %tr
          %td=f.label :name
          %td{:colspan =>2}=f.text_field :name

        %tr
          %td= f.label :period, "Repeats" 
          %td
            = f.select :period, Event::REPEATS, {}, :onchange => "showPeriodAndFrequency(this.value)"
        =render 'event_set_form', f: f

        %tr
          %td=f.label :from
          %td
            =f.text_field :fromdate, class: "span2"
            =f.text_field :fromtime, class: "span2"
      
        %tr
          %td=f.label :to
          %td
            =f.text_field :todate, class: "span2"
            =f.text_field :totime, class: "span2"

        %tr
          %td=f.label :position
          %td{:colspan =>2}=f.text_field :position

        %tr
          %td=f.label :desc
          %td{:colspan =>2}=f.text_area :desc, rows: 2, cols: 60

        %tr
          %td= f.label :allDay, "All day "
          %td
            = f.check_box :allDay

        %tr
          %td=f.label :color
          %td{:colspan =>2}=f.text_field :color, class: "color1"
        %tr
          %td= f.label :privacy
          %td= f.select :privacy, options_for_select([["Public"], "Work", "Private"])      

        
  .modal-footer
    %button.btn{"data-dismiss" => "modal", "aria-hidden" => "true"} Close
    -if @event.event_set
      =f.submit 'Update Only This Occurrence', :onclick => "document.getElementById('event_commit').value = this.value", class: "btn btn-primary btn-small"
      =f.submit 'Update All Occurrence', :onclick => "document.getElementById('event_commit').value = this.value", class: "btn btn-success btn-small"
      =f.submit 'Update All Following Occurrence', :onclick => "document.getElementById('event_commit').value = this.value", class: "btn btn-danger btn-small"
    -else
      =f.submit 'Update', :onclick => "document.getElementById('event_commit').value = this.value", class: "btn btn-primary btn-small"
  



%script{:type => "text/javascript"}

  $('#event_fromtime').prop('disabled',$('#event_allDay').is(':checked'))
  $('#event_totime').prop('disabled',$('#event_allDay').is(':checked'))

  $('#event_fromdate').datetimepicker({
  altField: "#event_fromtime",
  dateFormat: "dd-mm-yy",
  timeFormat: "hh:mm",
  });
  $('#event_todate').datetimepicker({
  altField: "#event_totime",
  dateFormat: "dd-mm-yy",
  timeFormat: "hh:mm"
  });
  $('.color1').colorPicker();
  $('#event_allDay').click(function(){
  var thisCheck = $(this)
  if(thisCheck.is(':checked')){
  $('#event_fromtime').val('')
  $('#event_fromtime').prop('disabled',true)
  $('#event_totime').val('')
  $('#event_totime').prop('disabled',true)
  }
  else{
  $('#event_fromtime').prop('disabled',false)
  $('#event_totime').prop('disabled',false)
  }
  })

app/views/events/_event_set_form.html.haml
%tr#frequency{:style => "display:none"}
	%td=f.label :frequency, "Repeat every"
	%td
		=f.select :frequency, (1..30).to_a
		%span#period
		=text_field_tag 'event[times]', nil, class: "times"
		times


		
		

app/views/events/_select_partner.html.haml
=form_tag  events_get_pevents_path, method: :post, class: "select-form" do
  .modal-header
    %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} ×
    %h3#myModalLabel Select partner
  .modal-body
    %table.table.table-striped.table-hover
      %th{:style =>"width: 20%"} Check
      %th Name
      -@users.each do |user|
        %tr
          %td
            =check_box_tag 'user_ids[]', user.id
          %td
            =user.name

  .modal-footer
    %button.btn{"data-dismiss" => "modal", "aria-hidden" => "true"} Close
    =submit_tag "View", class: "btn btn-primary"

app/views/events/destroy.js.erb
$('#calendar').fullCalendar( 'refetchEvents' )
$('#desc_dialog').dialog('destroy')

app/views/events/edit.js.erb
$('#desc_dialog').dialog('destroy')
$('#contentPopup').addClass('modal').css({ top: 300, width: 650}).html("<%=j render 'edit_form' %>").modal('show');

app/views/events/get_pevents.html.haml
-provide(:title, "Partner events")
.mybody
	.btn-group.page-header
		=link_to 'CREATE', new_event_path, class: "btn btn-large btn-success"
		=link_to 'PARTNER\'S CALENDAR', 'events/select_partner', remote: :true, class: "btn btn-large btn-primary"
	.span12
		#notation.well
			Users:
			-@users.each_with_index do |user,index|
				%strong=user.name
				#color{:style => "background-color: #{get_color(index)}"}
		#calendar1


%script{:type => 'text/javascript'}
	$(document).ready(function(){
	$('#calendar1').fullCalendar({
	editable: false,
	header: {
	left: 'prev,next today',
	center: 'title',
	right: 'month,agendaWeek,agendaDay'
	},
	defaultView: 'month',
	height: 600,
	width: 940,
	slotMinutes: 30,
	loading: function(bool){
	if (bool) 
	$('#loading').show();
	else 
	$('#loading').hide();
	},
	events: #{@pevents},
	timeFormat: 'h:mm t{ - h:mm t} ',	
	});
	});

app/views/events/new.html.haml
-provide(:title, 'New event')
.mybody
  %h1.page-header Create new event
.row
  .span6.offset3
    %table.mytable
      =form_for(@event) do |f| 
        = render 'shared/error_messages' , object: @event
        %tr
          %td=f.label :name
          %td{:colspan =>2}=f.text_field :name

        %tr
          %td= f.label :period, "Repeats" 
          %td
            = f.select :period, Event::REPEATS, {}, :onchange => "showPeriodAndFrequency(this.value)"
        =render 'event_set_form', f: f

        %tr
          %td=f.label :from
          %td
            =f.text_field :fromdate, class: "span2"
            =f.text_field :fromtime, class: "span2"
      
        %tr
          %td=f.label :to
          %td
            =f.text_field :todate, class: "span2"
            =f.text_field :totime, class: "span2"

        %tr
          %td=f.label :position
          %td{:colspan =>2}=f.text_field :position

        %tr
          %td=f.label :desc
          %td{:colspan =>2}=f.text_area :desc, rows: 2, cols: 60

        %tr
          %td= f.label :allDay, "All day "
          %td
            = f.check_box :allDay

        %tr
          %td=f.label :color
          %td{:colspan =>2}=f.text_field :color, class: "color1"
        %tr
          %td= f.label :privacy
          %td= f.select :privacy, options_for_select([["Public", 0], ["Work", 1], ["Private",2]])

                    
        %tr
          %td
          %td{:colspan =>3}= f.submit "Create", class: "btn btn-large btn-primary span6" 



%script{:type => "text/javascript"}

  $('#event_fromtime').prop('disabled',$('#event_allDay').is(':checked'))
  $('#event_totime').prop('disabled',$('#event_allDay').is(':checked'))

  $('#event_fromdate').datetimepicker({
  altField: "#event_fromtime",
  dateFormat: "dd-mm-yy",
  timeFormat: "hh:mm",
  });
  $('#event_todate').datetimepicker({
  altField: "#event_totime",
  dateFormat: "dd-mm-yy",
  timeFormat: "hh:mm"
  });
  $('.color1').colorPicker();
  $('#event_allDay').click(function(){
  var thisCheck = $(this)
  if(thisCheck.is(':checked')){
  $('#event_fromtime').val('')
  $('#event_fromtime').prop('disabled',true)
  $('#event_totime').val('')
  $('#event_totime').prop('disabled',true)
  }
  else{
  $('#event_fromtime').prop('disabled',false)
  $('#event_totime').prop('disabled',false)
  }
  })
 

app/views/events/select_partner.js.erb
$('#contentPopup').addClass('modal').css({ top: 300, width: 650}).html("<%=j render 'select_partner' %>").modal('show');

app/views/events/update.js.erb
$('#calendar').fullCalendar( 'refetchEvents' )
$('#desc_dialog').dialog('destroy')
$('#contentPopup').modal('hide')