config/routes.rb
Calendar::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :events, only: [:new,:create,:update,:destroy]

  root to: "static_pages#home"
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy", via: :delete

  match '/events/get_events'
  match '/events/resize'
  match '/events/move'
  match '/events/destroy'
  match '/events/edit'
  match '/events/select_partner'
  match '/events/get_pevents', via: :post

 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Calendar</a>
    by QuyenLQ
  </small>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%=root_path %>" id="logo">Calendar</a>
      <nav>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>          
          <% if signed_in? %>
          <li><%= link_to "Profile", current_user %></li>        
          <li class="divider-vertical"></li>
          <% if admin? %>
          <li><%= link_to "Create user", new_user_path %></li>
          <li class="divider-vertical"></li>
          <% end %>
          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
          <li class="divider-vertical"></li>
        </ul>
        <nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Calendar </title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %> 
</head>
<body>
	<%= render 'layouts/header' %>	
	<div class="container">
		<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
      	<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

  <div id="contentPopup">    
  </div>
</body>
</html>